name: Cloc by GitHub Actions

on:
  workflow_dispatch:

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: actions-cloc
      uses: maxfie1d/actions-cloc@v1
      with:
        artifact: true
